### ISSUE TITLE
[PATCH] spelling fix [rt.cpan.org #122996]

### ISSUE THREAD

**Issue by stsc** [stsc/LaTeX-TOM#3]
Migrated from [rt.cpan.org#122996](https://rt.cpan.org/Ticket/Display.html?id=122996) (status was 'new')

Requestors:
* gregoa@cpan.org

Attachments:
* [spelling.patch](https://rt.cpan.org/Ticket/Attachment/1747783/940141/spelling.patch)

From gregoa@cpan.org on 2017-09-09 18:13:50
:
```
In Debian we are currently applying the following patch to LaTeX-TOM.
We thought you might be interested in it too.

Description: spelling fix
Origin: vendor
Author: gregor herrmann <gregoa@debian.org>
Last-Update: 2017-09-09


The patch is tracked in our Git repository at
https://anonscm.debian.org/cgit/pkg-perl/packages/liblatex-tom-perl.git/plain/debian/patches/spelling.patch

Thanks for considering,
  gregor herrmann,
  Debian Perl Group


```

From gregoa@cpan.org on 2017-09-09 18:13:51
:
```
Here's the patch.
```

**Comment by gregoa** [comment]
The repo with the patch moved as well, the new location is:
https://salsa.debian.org/perl-team/modules/packages/liblatex-tom-perl/-/blob/master/debian/patches/spelling.patch

**Comment by stsc** [comment]
Thanks, applied in `v1.03_05`.  Closing.
